import { SeriesData, RaceEvent } from '../types';

const currentYear = 2025;

// Formula 1 sample data - 2025 Calendar (Complete 24-race season)
const f1RaceEvents: RaceEvent[] = [
  {
    id: 'f1-australia-2025',
    series: 'f1',
    name: 'Australian Grand Prix',
    date: '2025-03-16T05:00:00Z',
    location: {
      name: 'Albert Park Circuit',
      city: 'Melbourne',
      country: 'Australia',
      coordinates: {
        lat: -37.8497,
        lng: 144.968,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 15,
      windSpeed: 12,
      airPressure: 1012,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-china-2025',
    series: 'f1',
    name: 'Chinese Grand Prix',
    date: '2025-03-23T07:00:00Z',
    location: {
      name: 'Shanghai International Circuit',
      city: 'Shanghai',
      country: 'China',
      coordinates: {
        lat: 31.3389,
        lng: 121.2205,
      },
    },
    weatherData: {
      temperature: 18,
      rainChance: 30,
      windSpeed: 15,
      airPressure: 1014,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-japan-2025',
    series: 'f1',
    name: 'Japanese Grand Prix',
    date: '2025-04-06T06:00:00Z',
    location: {
      name: 'Suzuka International Racing Course',
      city: 'Suzuka',
      country: 'Japan',
      coordinates: {
        lat: 34.8431,
        lng: 136.5410,
      },
    },
    weatherData: {
      temperature: 16,
      rainChance: 25,
      windSpeed: 10,
      airPressure: 1011,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-bahrain-2025',
    series: 'f1',
    name: 'Bahrain Grand Prix',
    date: '2025-04-13T16:00:00Z',
    location: {
      name: 'Bahrain International Circuit',
      city: 'Sakhir',
      country: 'Bahrain',
      coordinates: {
        lat: 26.0325,
        lng: 50.5106,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 0,
      windSpeed: 15,
      airPressure: 1010,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-saudi-arabia-2025',
    series: 'f1',
    name: 'Saudi Arabian Grand Prix',
    date: '2025-04-20T17:00:00Z',
    location: {
      name: 'Jeddah Corniche Circuit',
      city: 'Jeddah',
      country: 'Saudi Arabia',
      coordinates: {
        lat: 21.6319,
        lng: 39.1044,
      },
    },
    weatherData: {
      temperature: 29,
      rainChance: 0,
      windSpeed: 12,
      airPressure: 1009,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-miami-2025',
    series: 'f1',
    name: 'Miami Grand Prix',
    date: '2025-05-04T19:00:00Z',
    location: {
      name: 'Miami International Autodrome',
      city: 'Miami Gardens',
      country: 'United States',
      coordinates: {
        lat: 25.9581,
        lng: -80.2389,
      },
    },
    weatherData: {
      temperature: 28,
      rainChance: 20,
      windSpeed: 8,
      airPressure: 1013,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-emilia-romagna-2025',
    series: 'f1',
    name: 'Emilia Romagna Grand Prix',
    date: '2025-05-18T13:00:00Z',
    location: {
      name: 'Imola Circuit',
      city: 'Imola',
      country: 'Italy',
      coordinates: {
        lat: 44.3439,
        lng: 11.7167,
      },
    },
    weatherData: {
      temperature: 23,
      rainChance: 15,
      windSpeed: 7,
      airPressure: 1015,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-monaco-2025',
    series: 'f1',
    name: 'Monaco Grand Prix',
    date: '2025-05-25T13:00:00Z',
    location: {
      name: 'Circuit de Monaco',
      city: 'Monaco',
      country: 'Monaco',
      coordinates: {
        lat: 43.7347,
        lng: 7.4206,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 10,
      windSpeed: 5,
      airPressure: 1016,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-spain-2025',
    series: 'f1',
    name: 'Spanish Grand Prix',
    date: '2025-06-01T13:00:00Z',
    location: {
      name: 'Circuit de Barcelona-Catalunya',
      city: 'Montmeló',
      country: 'Spain',
      coordinates: {
        lat: 41.5638,
        lng: 2.2585,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 5,
      windSpeed: 8,
      airPressure: 1017,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-canada-2025',
    series: 'f1',
    name: 'Canadian Grand Prix',
    date: '2025-06-15T18:00:00Z',
    location: {
      name: 'Circuit Gilles Villeneuve',
      city: 'Montreal',
      country: 'Canada',
      coordinates: {
        lat: 45.5017,
        lng: -73.5673,
      },
    },
    weatherData: {
      temperature: 20,
      rainChance: 30,
      windSpeed: 12,
      airPressure: 1012,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-austria-2025',
    series: 'f1',
    name: 'Austrian Grand Prix',
    date: '2025-06-29T13:00:00Z',
    location: {
      name: 'Red Bull Ring',
      city: 'Spielberg',
      country: 'Austria',
      coordinates: {
        lat: 47.2197,
        lng: 14.7647,
      },
    },
    weatherData: {
      temperature: 24,
      rainChance: 35,
      windSpeed: 6,
      airPressure: 1013,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-britain-2025',
    series: 'f1',
    name: 'British Grand Prix',
    date: '2025-07-06T14:00:00Z',
    location: {
      name: 'Silverstone Circuit',
      city: 'Silverstone',
      country: 'United Kingdom',
      coordinates: {
        lat: 52.0786,
        lng: -1.0169,
      },
    },
    weatherData: {
      temperature: 19,
      rainChance: 40,
      windSpeed: 15,
      airPressure: 1011,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-belgium-2025',
    series: 'f1',
    name: 'Belgian Grand Prix',
    date: '2025-07-27T13:00:00Z',
    location: {
      name: 'Circuit de Spa-Francorchamps',
      city: 'Stavelot',
      country: 'Belgium',
      coordinates: {
        lat: 50.4372,
        lng: 5.9714,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 45,
      windSpeed: 10,
      airPressure: 1012,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-hungary-2025',
    series: 'f1',
    name: 'Hungarian Grand Prix',
    date: '2025-08-03T13:00:00Z',
    location: {
      name: 'Hungaroring',
      city: 'Mogyoród',
      country: 'Hungary',
      coordinates: {
        lat: 47.5830,
        lng: 19.2526,
      },
    },
    weatherData: {
      temperature: 30,
      rainChance: 20,
      windSpeed: 8,
      airPressure: 1015,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-netherlands-2025',
    series: 'f1',
    name: 'Dutch Grand Prix',
    date: '2025-08-31T13:00:00Z',
    location: {
      name: 'Circuit Zandvoort',
      city: 'Zandvoort',
      country: 'Netherlands',
      coordinates: {
        lat: 52.3888,
        lng: 4.5474,
      },
    },
    weatherData: {
      temperature: 21,
      rainChance: 30,
      windSpeed: 20,
      airPressure: 1010,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-italy-2025',
    series: 'f1',
    name: 'Italian Grand Prix',
    date: '2025-09-07T13:00:00Z',
    location: {
      name: 'Monza Circuit',
      city: 'Monza',
      country: 'Italy',
      coordinates: {
        lat: 45.6223,
        lng: 9.2800,
      },
    },
    weatherData: {
      temperature: 27,
      rainChance: 15,
      windSpeed: 5,
      airPressure: 1014,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-azerbaijan-2025',
    series: 'f1',
    name: 'Azerbaijan Grand Prix',
    date: '2025-09-21T12:00:00Z',
    location: {
      name: 'Baku City Circuit',
      city: 'Baku',
      country: 'Azerbaijan',
      coordinates: {
        lat: 40.3724,
        lng: 49.8533,
      },
    },
    weatherData: {
      temperature: 24,
      rainChance: 5,
      windSpeed: 18,
      airPressure: 1013,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-singapore-2025',
    series: 'f1',
    name: 'Singapore Grand Prix',
    date: '2025-10-05T12:00:00Z',
    location: {
      name: 'Marina Bay Street Circuit',
      city: 'Singapore',
      country: 'Singapore',
      coordinates: {
        lat: 1.2914,
        lng: 103.8644,
      },
    },
    weatherData: {
      temperature: 30,
      rainChance: 50,
      windSpeed: 5,
      airPressure: 1008,
      humidity: 85,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-usa-2025',
    series: 'f1',
    name: 'United States Grand Prix',
    date: '2025-10-19T19:00:00Z',
    location: {
      name: 'Circuit of the Americas',
      city: 'Austin',
      country: 'United States',
      coordinates: {
        lat: 30.1328,
        lng: -97.6411,
      },
    },
    weatherData: {
      temperature: 25,
      rainChance: 15,
      windSpeed: 10,
      airPressure: 1012,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-mexico-2025',
    series: 'f1',
    name: 'Mexico City Grand Prix',
    date: '2025-10-26T20:00:00Z',
    location: {
      name: 'Autódromo Hermanos Rodríguez',
      city: 'Mexico City',
      country: 'Mexico',
      coordinates: {
        lat: 19.4042,
        lng: -99.0907,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 10,
      windSpeed: 7,
      airPressure: 1015,
      humidity: 45,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-brazil-2025',
    series: 'f1',
    name: 'São Paulo Grand Prix',
    date: '2025-11-09T17:00:00Z',
    location: {
      name: 'Interlagos Circuit',
      city: 'São Paulo',
      country: 'Brazil',
      coordinates: {
        lat: -23.7036,
        lng: -46.6997,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 35,
      windSpeed: 12,
      airPressure: 1011,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-las-vegas-2025',
    series: 'f1',
    name: 'Las Vegas Grand Prix',
    date: '2025-11-22T06:00:00Z',
    location: {
      name: 'Las Vegas Strip Circuit',
      city: 'Paradise',
      country: 'United States',
      coordinates: {
        lat: 36.1147,
        lng: -115.1728,
      },
    },
    weatherData: {
      temperature: 14,
      rainChance: 5,
      windSpeed: 15,
      airPressure: 1016,
      humidity: 40,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-qatar-2025',
    series: 'f1',
    name: 'Qatar Grand Prix',
    date: '2025-11-30T15:00:00Z',
    location: {
      name: 'Lusail International Circuit',
      city: 'Lusail',
      country: 'Qatar',
      coordinates: {
        lat: 25.4882,
        lng: 51.4541,
      },
    },
    weatherData: {
      temperature: 25,
      rainChance: 0,
      windSpeed: 12,
      airPressure: 1012,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f1-abu-dhabi-2025',
    series: 'f1',
    name: 'Abu Dhabi Grand Prix',
    date: '2025-12-07T13:00:00Z',
    location: {
      name: 'Yas Marina Circuit',
      city: 'Abu Dhabi',
      country: 'United Arab Emirates',
      coordinates: {
        lat: 24.4672,
        lng: 54.6031,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 0,
      windSpeed: 10,
      airPressure: 1013,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  }
];

// WRC sample data - 2025 Calendar
const wrcRaceEvents: RaceEvent[] = [
  {
    id: 'wrc-monte-carlo-2025',
    series: 'wrc',
    name: 'Rallye Automobile Monte Carlo',
    date: '2025-01-23T08:00:00Z',
    location: {
      name: 'Monte Carlo',
      city: 'Gap',
      country: 'France',
      coordinates: {
        lat: 44.5638,
        lng: 6.0789,
      },
    },
    weatherData: {
      temperature: 5,
      rainChance: 20,
      windSpeed: 8,
      airPressure: 1020,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-sweden-2025',
    series: 'wrc',
    name: 'Rally Sweden',
    date: '2025-02-13T08:00:00Z',
    location: {
      name: 'Umeå',
      city: 'Umeå',
      country: 'Sweden',
      coordinates: {
        lat: 63.8258,
        lng: 20.2630,
      },
    },
    weatherData: {
      temperature: -5,
      rainChance: 10,
      windSpeed: 15,
      airPressure: 1015,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-kenya-2025',
    series: 'wrc',
    name: 'Safari Rally Kenya',
    date: '2025-03-20T06:00:00Z',
    location: {
      name: 'Safari Rally',
      city: 'Nairobi',
      country: 'Kenya',
      coordinates: {
        lat: -1.2921,
        lng: 36.8219,
      },
    },
    weatherData: {
      temperature: 28,
      rainChance: 35,
      windSpeed: 7,
      airPressure: 1010,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-spain-canarias-2025',
    series: 'wrc',
    name: 'Rally Islas Canarias',
    date: '2025-04-24T07:00:00Z',
    location: {
      name: 'Gran Canaria',
      city: 'Las Palmas',
      country: 'Spain',
      coordinates: {
        lat: 28.1248,
        lng: -15.4300,
      },
    },
    weatherData: {
      temperature: 21,
      rainChance: 10,
      windSpeed: 12,
      airPressure: 1016,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-portugal-2025',
    series: 'wrc',
    name: 'Rally de Portugal',
    date: '2025-05-15T07:00:00Z',
    location: {
      name: 'Matosinhos',
      city: 'Porto',
      country: 'Portugal',
      coordinates: {
        lat: 41.1827,
        lng: -8.6951,
      },
    },
    weatherData: {
      temperature: 20,
      rainChance: 15,
      windSpeed: 12,
      airPressure: 1014,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-italy-sardinia-2025',
    series: 'wrc',
    name: 'Rally Italia Sardegna',
    date: '2025-06-05T07:00:00Z',
    location: {
      name: 'Sardinia',
      city: 'Olbia',
      country: 'Italy',
      coordinates: {
        lat: 40.9239,
        lng: 9.4907,
      },
    },
    weatherData: {
      temperature: 23,
      rainChance: 5,
      windSpeed: 15,
      airPressure: 1016,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-greece-2025',
    series: 'wrc',
    name: 'Acropolis Rally Greece',
    date: '2025-06-26T07:00:00Z',
    location: {
      name: 'Acropolis Rally',
      city: 'Lamia',
      country: 'Greece',
      coordinates: {
        lat: 38.8996,
        lng: 22.4334,
      },
    },
    weatherData: {
      temperature: 30,
      rainChance: 5,
      windSpeed: 10,
      airPressure: 1012,
      humidity: 45,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-estonia-2025',
    series: 'wrc',
    name: 'Rally Estonia',
    date: '2025-07-17T07:00:00Z',
    location: {
      name: 'Tartu',
      city: 'Tartu',
      country: 'Estonia',
      coordinates: {
        lat: 58.3780,
        lng: 26.7290,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 30,
      windSpeed: 8,
      airPressure: 1013,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-finland-2025',
    series: 'wrc',
    name: 'Rally Finland',
    date: '2025-07-31T07:00:00Z',
    location: {
      name: 'Jyväskylä',
      city: 'Jyväskylä',
      country: 'Finland',
      coordinates: {
        lat: 62.2426,
        lng: 25.7473,
      },
    },
    weatherData: {
      temperature: 20,
      rainChance: 25,
      windSpeed: 10,
      airPressure: 1012,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-paraguay-2025',
    series: 'wrc',
    name: 'Rally del Paraguay',
    date: '2025-08-28T07:00:00Z',
    location: {
      name: 'Encarnación',
      city: 'Encarnación',
      country: 'Paraguay',
      coordinates: {
        lat: -27.3306,
        lng: -55.8667,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 15,
      windSpeed: 7,
      airPressure: 1014,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-chile-2025',
    series: 'wrc',
    name: 'Rally Chile',
    date: '2025-09-11T07:00:00Z',
    location: {
      name: 'Biobío',
      city: 'Concepción',
      country: 'Chile',
      coordinates: {
        lat: -36.8270,
        lng: -73.0498,
      },
    },
    weatherData: {
      temperature: 16,
      rainChance: 40,
      windSpeed: 12,
      airPressure: 1011,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-central-european-2025',
    series: 'wrc',
    name: 'Central European Rally',
    date: '2025-10-16T07:00:00Z',
    location: {
      name: 'Bad Griesbach',
      city: 'Bavaria',
      country: 'Germany',
      coordinates: {
        lat: 48.4433,
        lng: 13.1989,
      },
    },
    weatherData: {
      temperature: 12,
      rainChance: 35,
      windSpeed: 10,
      airPressure: 1015,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-japan-2025',
    series: 'wrc',
    name: 'Rally Japan',
    date: '2025-11-06T08:00:00Z',
    location: {
      name: 'Toyota',
      city: 'Aichi',
      country: 'Japan',
      coordinates: {
        lat: 35.0826,
        lng: 137.1570,
      },
    },
    weatherData: {
      temperature: 14,
      rainChance: 45,
      windSpeed: 8,
      airPressure: 1016,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wrc-saudi-arabia-2025',
    series: 'wrc',
    name: 'Rally Saudi Arabia',
    date: '2025-11-27T08:00:00Z',
    location: {
      name: 'Jeddah',
      city: 'Jeddah',
      country: 'Saudi Arabia',
      coordinates: {
        lat: 21.4858,
        lng: 39.1925,
      },
    },
    weatherData: {
      temperature: 28,
      rainChance: 0,
      windSpeed: 12,
      airPressure: 1012,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  }
];

// MotoGP sample data - 2025 Calendar
const motoGPRaceEvents: RaceEvent[] = [
  {
    id: 'motogp-thailand-2025',
    series: 'motogp',
    name: 'PT Grand Prix of Thailand',
    date: '2025-03-02T07:00:00Z',
    location: {
      name: 'Chang International Circuit',
      city: 'Buriram',
      country: 'Thailand',
      coordinates: {
        lat: 14.9971,
        lng: 103.0777,
      },
    },
    weatherData: {
      temperature: 32,
      rainChance: 15,
      windSpeed: 8,
      airPressure: 1010,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-argentina-2025',
    series: 'motogp',
    name: 'Gran Premio YPF Energía de Argentina',
    date: '2025-03-16T19:00:00Z',
    location: {
      name: 'Autódromo Termas de Río Hondo',
      city: 'Termas de Río Hondo',
      country: 'Argentina',
      coordinates: {
        lat: -27.5089,
        lng: -64.9158,
      },
    },
    weatherData: {
      temperature: 24,
      rainChance: 30,
      windSpeed: 10,
      airPressure: 1012,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-americas-2025',
    series: 'motogp',
    name: 'Red Bull Grand Prix of the Americas',
    date: '2025-03-30T18:00:00Z',
    location: {
      name: 'Circuit of the Americas',
      city: 'Austin',
      country: 'United States',
      coordinates: {
        lat: 30.1328,
        lng: -97.6411,
      },
    },
    weatherData: {
      temperature: 23,
      rainChance: 15,
      windSpeed: 12,
      airPressure: 1013,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-qatar-2025',
    series: 'motogp',
    name: 'Qatar Airways Grand Prix of Qatar',
    date: '2025-04-13T17:00:00Z',
    location: {
      name: 'Lusail International Circuit',
      city: 'Lusail',
      country: 'Qatar',
      coordinates: {
        lat: 25.4882,
        lng: 51.4541,
      },
    },
    weatherData: {
      temperature: 27,
      rainChance: 0,
      windSpeed: 15,
      airPressure: 1010,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-spain-2025',
    series: 'motogp',
    name: 'Gran Premio Estrella Galicia 0,0 de España',
    date: '2025-04-27T13:00:00Z',
    location: {
      name: 'Circuito de Jerez – Ángel Nieto',
      city: 'Jerez de la Frontera',
      country: 'Spain',
      coordinates: {
        lat: 36.7083,
        lng: -6.0415,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 5,
      windSpeed: 10,
      airPressure: 1016,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-france-2025',
    series: 'motogp',
    name: 'Michelin Grand Prix de France',
    date: '2025-05-11T13:00:00Z',
    location: {
      name: 'Bugatti Circuit',
      city: 'Le Mans',
      country: 'France',
      coordinates: {
        lat: 47.9561,
        lng: 0.2266,
      },
    },
    weatherData: {
      temperature: 18,
      rainChance: 35,
      windSpeed: 15,
      airPressure: 1014,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-uk-2025',
    series: 'motogp',
    name: 'Tissot British Grand Prix',
    date: '2025-05-25T13:00:00Z',
    location: {
      name: 'Silverstone Circuit',
      city: 'Silverstone',
      country: 'United Kingdom',
      coordinates: {
        lat: 52.0786,
        lng: -1.0169,
      },
    },
    weatherData: {
      temperature: 17,
      rainChance: 40,
      windSpeed: 18,
      airPressure: 1011,
      humidity: 75,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-aragon-2025',
    series: 'motogp',
    name: 'Gran Premio GoPro de Aragón',
    date: '2025-06-08T13:00:00Z',
    location: {
      name: 'MotorLand Aragón',
      city: 'Alcañiz',
      country: 'Spain',
      coordinates: {
        lat: 41.0782,
        lng: -0.2013,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 5,
      windSpeed: 12,
      airPressure: 1015,
      humidity: 45,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-italy-2025',
    series: 'motogp',
    name: 'Gran Premio d\'Italia Brembo',
    date: '2025-06-22T13:00:00Z',
    location: {
      name: 'Autodromo Internazionale del Mugello',
      city: 'Scarperia e San Piero',
      country: 'Italy',
      coordinates: {
        lat: 43.9975,
        lng: 11.3719,
      },
    },
    weatherData: {
      temperature: 25,
      rainChance: 10,
      windSpeed: 8,
      airPressure: 1015,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-netherlands-2025',
    series: 'motogp',
    name: 'Motul TT Assen',
    date: '2025-06-29T13:00:00Z',
    location: {
      name: 'TT Circuit Assen',
      city: 'Assen',
      country: 'Netherlands',
      coordinates: {
        lat: 52.9612,
        lng: 6.5250,
      },
    },
    weatherData: {
      temperature: 21,
      rainChance: 30,
      windSpeed: 14,
      airPressure: 1012,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-germany-2025',
    series: 'motogp',
    name: 'Liqui Moly Motorrad Grand Prix Deutschland',
    date: '2025-07-13T13:00:00Z',
    location: {
      name: 'Sachsenring',
      city: 'Hohenstein-Ernstthal',
      country: 'Germany',
      coordinates: {
        lat: 50.7892,
        lng: 12.6913,
      },
    },
    weatherData: {
      temperature: 24,
      rainChance: 25,
      windSpeed: 10,
      airPressure: 1013,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-czech-2025',
    series: 'motogp',
    name: 'Grand Prix of Czechia',
    date: '2025-07-20T13:00:00Z',
    location: {
      name: 'Brno Circuit',
      city: 'Brno',
      country: 'Czech Republic',
      coordinates: {
        lat: 49.2046,
        lng: 16.4506,
      },
    },
    weatherData: {
      temperature: 25,
      rainChance: 20,
      windSpeed: 8,
      airPressure: 1014,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-austria-2025',
    series: 'motogp',
    name: 'Motorrad Grand Prix von Österreich',
    date: '2025-08-17T13:00:00Z',
    location: {
      name: 'Red Bull Ring',
      city: 'Spielberg',
      country: 'Austria',
      coordinates: {
        lat: 47.2197,
        lng: 14.7647,
      },
    },
    weatherData: {
      temperature: 26,
      rainChance: 30,
      windSpeed: 7,
      airPressure: 1013,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-hungary-2025',
    series: 'motogp',
    name: 'Grand Prix of Hungary',
    date: '2025-08-24T13:00:00Z',
    location: {
      name: 'Balaton Park Circuit',
      city: 'Balatonfőkajár',
      country: 'Hungary',
      coordinates: {
        lat: 46.9929,
        lng: 18.2315,
      },
    },
    weatherData: {
      temperature: 27,
      rainChance: 15,
      windSpeed: 8,
      airPressure: 1014,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-catalonia-2025',
    series: 'motogp',
    name: 'Gran Premi Monster Energy de Catalunya',
    date: '2025-09-07T13:00:00Z',
    location: {
      name: 'Circuit de Barcelona-Catalunya',
      city: 'Montmeló',
      country: 'Spain',
      coordinates: {
        lat: 41.5704,
        lng: 2.2608,
      },
    },
    weatherData: {
      temperature: 25,
      rainChance: 10,
      windSpeed: 10,
      airPressure: 1017,
      humidity: 50,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-san-marino-2025',
    series: 'motogp',
    name: 'Gran Premio Red Bull di San Marino e della Riviera di Rimini',
    date: '2025-09-14T13:00:00Z',
    location: {
      name: 'Misano World Circuit Marco Simoncelli',
      city: 'Misano Adriatico',
      country: 'Italy',
      coordinates: {
        lat: 43.9611,
        lng: 12.6839,
      },
    },
    weatherData: {
      temperature: 24,
      rainChance: 15,
      windSpeed: 9,
      airPressure: 1015,
      humidity: 55,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-japan-2025',
    series: 'motogp',
    name: 'Motul Grand Prix of Japan',
    date: '2025-09-28T05:00:00Z',
    location: {
      name: 'Mobility Resort Motegi',
      city: 'Motegi',
      country: 'Japan',
      coordinates: {
        lat: 36.5341,
        lng: 140.2277,
      },
    },
    weatherData: {
      temperature: 22,
      rainChance: 25,
      windSpeed: 11,
      airPressure: 1014,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-indonesia-2025',
    series: 'motogp',
    name: 'Pertamina Grand Prix of Indonesia',
    date: '2025-10-05T07:00:00Z',
    location: {
      name: 'Pertamina Mandalika International Street Circuit',
      city: 'Mandalika',
      country: 'Indonesia',
      coordinates: {
        lat: -8.8965,
        lng: 116.3017,
      },
    },
    weatherData: {
      temperature: 30,
      rainChance: 40,
      windSpeed: 10,
      airPressure: 1009,
      humidity: 80,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-australia-2025',
    series: 'motogp',
    name: 'Australian Motorcycle Grand Prix',
    date: '2025-10-19T04:00:00Z',
    location: {
      name: 'Phillip Island Grand Prix Circuit',
      city: 'Phillip Island',
      country: 'Australia',
      coordinates: {
        lat: -38.5019,
        lng: 145.2329,
      },
    },
    weatherData: {
      temperature: 18,
      rainChance: 35,
      windSpeed: 20,
      airPressure: 1010,
      humidity: 70,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-malaysia-2025',
    series: 'motogp',
    name: 'Petronas Grand Prix of Malaysia',
    date: '2025-10-26T07:00:00Z',
    location: {
      name: 'Petronas Sepang International Circuit',
      city: 'Sepang',
      country: 'Malaysia',
      coordinates: {
        lat: 2.7602,
        lng: 101.7382,
      },
    },
    weatherData: {
      temperature: 32,
      rainChance: 60,
      windSpeed: 8,
      airPressure: 1008,
      humidity: 85,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-portugal-2025',
    series: 'motogp',
    name: 'Qatar Airways Grande Prémio de Portugal',
    date: '2025-11-09T13:00:00Z',
    location: {
      name: 'Algarve International Circuit',
      city: 'Portimão',
      country: 'Portugal',
      coordinates: {
        lat: 37.2300,
        lng: -8.6267,
      },
    },
    weatherData: {
      temperature: 19,
      rainChance: 30,
      windSpeed: 12,
      airPressure: 1016,
      humidity: 65,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'motogp-valencia-2025',
    series: 'motogp',
    name: 'Gran Premio Motul de la Comunitat Valenciana',
    date: '2025-11-16T13:00:00Z',
    location: {
      name: 'Circuit Ricardo Tormo',
      city: 'Valencia',
      country: 'Spain',
      coordinates: {
        lat: 39.4856,
        lng: -0.6271,
      },
    },
    weatherData: {
      temperature: 17,
      rainChance: 20,
      windSpeed: 10,
      airPressure: 1017,
      humidity: 60,
      updatedAt: new Date().toISOString(),
    },
    updatedAt: new Date().toISOString(),
  }
];

// Combined series data
export const seriesData: SeriesData[] = [
  {
    id: 'f1',
    name: 'Formula 1',
    currentSeason: currentYear.toString(),
    races: f1RaceEvents,
  },
  {
    id: 'wrc',
    name: 'World Rally Championship',
    currentSeason: currentYear.toString(),
    races: wrcRaceEvents,
  },
  {
    id: 'motogp',
    name: 'MotoGP',
    currentSeason: currentYear.toString(),
    races: motoGPRaceEvents,
  },
];

export function getSeriesById(id: string): SeriesData | undefined {
  return seriesData.find(series => series.id === id);
} 